services:

    Jul6Art\CoreBundle\EntityListener\AbstractEntityListener:
        abstract: true
        calls:
            - setRequestStack: ['@request_stack']
            - setTokenStorage: ['@security.token_storage']
            - setTranslator: ['@translator']

    Jul6Art\CoreBundle\EventListener\AbstractEventListener:
        abstract: true
        calls:
            - setTokenStorage: ['@security.token_storage']
