<?php

declare(strict_types=1);

namespace Jul6Art\CoreBundle\DependencyInjection;

use Jul6Art\CoreBundle\Logger\QueryStringRedactingProcessor;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Class Configuration.
 */
class Configuration implements ConfigurationInterface
{
    #[\Override]
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('core');

        $treeBuilder->getRootNode()
            ->children()
                ->booleanNode('email_debug')
                    ->info('Forwards critical logs by email through Monolog.')
                    ->defaultFalse()
                ->end()
                ->scalarNode('email_debug_from')
                    ->info('Sender address. Required when email_debug is enabled.')
                    ->defaultNull()
                ->end()
                ->scalarNode('email_debug_title')
                    ->info('Subject of the debug emails.')
                    ->defaultValue('An error occured')
                ->end()
                ->scalarNode('email_debug_to')
                    ->info('Recipient address. Required when email_debug is enabled.')
                    ->defaultNull()
                ->end()
                ->arrayNode('flash')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_domain')
                            ->info('Domain used when no prefix matches.')
                            ->defaultValue('messages')
                        ->end()
                        ->arrayNode('domain_map')
                            ->info('Flash key prefix => translation domain. ORDER MATTERS: the first match wins, so declare a longer prefix before the shorter one it starts with.')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('js_translations')
                    ->info('The bridge to symfony/ux-translator: which translation domain the browser is allowed to see. Inert until that package is installed.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('On by default, and it only ever does anything when UxTranslatorBundle is registered. Turn it off to keep the package\'s own behaviour — every domain dumped into the browser bundle.')
                            ->defaultTrue()
                        ->end()
                        ->scalarNode('domain')
                            ->info('THE domain exposed to JavaScript. One, deliberately: a domain answers "who reads this label", so a key the browser needs is moved into it rather than exposed where it lies.')
                            ->defaultValue('javascript')
                            ->cannotBeEmpty()
                        ->end()
                        ->scalarNode('dump_directory')
                            ->info('Where ux-translator writes index.js. Must exist before the front-end build runs: it is an import of assets/translator.js.')
                            ->defaultValue('%kernel.project_dir%/var/translations')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('number_format')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('decimal_separator')
                            ->info('Defaults to the French convention.')
                            ->defaultValue(',')
                        ->end()
                        ->scalarNode('thousands_separator')
                            ->info('Defaults to a non-breaking space: reads as a space, but never lets a PDF renderer wrap a number.')
                            ->defaultValue("\u{00A0}")
                        ->end()
                        ->integerNode('decimals')
                            ->info('Decimals shown by default. The database may keep more for computation.')
                            ->min(0)
                            ->defaultValue(2)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('form')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('number_grouping')
                            ->info('Turns on thousands grouping for every NumberType. Off by default: it changes how every numeric field of the application looks.')
                            ->defaultFalse()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('log_redaction')
                    ->info('Redacts the VALUE of sensitive query parameters (signed-link secrets, search terms) from every log record. On by default: it can only hide a value, never break a response.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->arrayNode('parameters')
                            ->info('Query parameter names whose value is redacted, case-insensitively. Replaces the default list: repeat the defaults to extend it.')
                            ->scalarPrototype()->end()
                            ->defaultValue(QueryStringRedactingProcessor::DEFAULT_PARAMETERS)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security_headers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Off by default: installing this bundle must not change the responses of an application that did not ask for these headers. A real boolean only — it decides whether the listener is registered at all, which happens at compile time, so an env var cannot answer it.')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('csp_enforce')
                            ->info('false sends Content-Security-Policy-Report-Only. Watch the reports, then flip it. Scalar rather than boolean so it accepts %env(bool:…)%, resolved at runtime.')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('csp_policy')
                            ->info('Full policy string. null uses the bundle default, which keeps connect-src closed.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('headers')
                            ->info('Overrides merged over the defaults. A null value drops that header entirely.')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('captcha')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('operations')
                            ->info('Arithmetic operations the question may use: +, - or *.')
                            ->scalarPrototype()->end()
                            ->defaultValue(['+'])
                        ->end()
                        ->scalarNode('session_key')
                            ->info('Session key holding the expected answer.')
                            ->defaultValue('_math_captcha_answer')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('purge')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('batch_size')
                            ->info('Rows flushed at a time by core:purge. Lower it when the entities are heavy.')
                            ->min(1)
                            ->defaultValue(100)
                        ->end()
                        ->arrayNode('aliases')
                            ->info('Extra names core:purge answers to. Use it to keep a legacy name alive so a deployed crontab does not break.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('performance')
                    ->info('Per-request performance profiler: a DBAL middleware counts the queries, a subscriber writes one JSONL record per request, and a data collector shows the panel in the web debug toolbar.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Master switch. When false the middleware still resets its tracker each request (no leak across requests) but NOTHING is persisted and the panel stays empty. Keep it off in production unless you are deliberately profiling: the store grows with every request.')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('path')
                            ->info('Directory of the append-only JSONL store. Must be writable by the web user and excluded from version control.')
                            ->defaultValue('%kernel.project_dir%/var/performance')
                            ->cannotBeEmpty()
                        ->end()
                        ->enumNode('rotation')
                            ->info('How records are split across files.')
                            ->values(['daily', 'weekly', 'none'])
                            ->defaultValue('daily')
                        ->end()
                        ->integerNode('max_records')
                            ->info('Above this many records the oldest file is pruned. A cap, not a target.')
                            ->min(1)
                            ->defaultValue(100000)
                        ->end()
                        ->scalarNode('ignored_route_prefix')
                            ->info('Routes starting with this prefix are not recorded — the profiler UI itself, which would otherwise measure its own dashboard. Empty records everything.')
                            ->defaultValue('admin_performance_')
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('encryption_key')
                    ->info('Base64-encoded 32-byte key. Setting it registers Security\\Encryptor and the listener that feeds the encrypted_string DBAL type. Point it at an env var; never commit it.')
                    ->defaultNull()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
