<?php

declare(strict_types=1);

namespace Jul6Art\CoreBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Class Configuration.
 */
class Configuration implements ConfigurationInterface
{
    #[\Override]
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('core');

        $treeBuilder->getRootNode()
            ->children()
                ->booleanNode('email_debug')
                    ->info('Forwards critical logs by email through Monolog.')
                    ->defaultFalse()
                ->end()
                ->scalarNode('email_debug_from')
                    ->info('Sender address. Required when email_debug is enabled.')
                    ->defaultNull()
                ->end()
                ->scalarNode('email_debug_title')
                    ->info('Subject of the debug emails.')
                    ->defaultValue('An error occured')
                ->end()
                ->scalarNode('email_debug_to')
                    ->info('Recipient address. Required when email_debug is enabled.')
                    ->defaultNull()
                ->end()
                ->arrayNode('flash')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_domain')
                            ->info('Domain used when no prefix matches.')
                            ->defaultValue('messages')
                        ->end()
                        ->arrayNode('domain_map')
                            ->info('Flash key prefix => translation domain. ORDER MATTERS: the first match wins, so declare a longer prefix before the shorter one it starts with.')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('number_format')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('decimal_separator')
                            ->info('Defaults to the French convention.')
                            ->defaultValue(',')
                        ->end()
                        ->scalarNode('thousands_separator')
                            ->info('Defaults to a non-breaking space: reads as a space, but never lets a PDF renderer wrap a number.')
                            ->defaultValue("\u{00A0}")
                        ->end()
                        ->integerNode('decimals')
                            ->info('Decimals shown by default. The database may keep more for computation.')
                            ->min(0)
                            ->defaultValue(2)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('form')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('number_grouping')
                            ->info('Turns on thousands grouping for every NumberType. Off by default: it changes how every numeric field of the application looks.')
                            ->defaultFalse()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('pdf')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('public_dir')
                            ->info('Directory the PDF asset helpers resolve paths against.')
                            ->defaultValue('%kernel.project_dir%/public')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security_headers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Off by default: installing this bundle must not change the responses of an application that did not ask for these headers. A real boolean only — it decides whether the listener is registered at all, which happens at compile time, so an env var cannot answer it.')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('csp_enforce')
                            ->info('false sends Content-Security-Policy-Report-Only. Watch the reports, then flip it. Scalar rather than boolean so it accepts %env(bool:…)%, resolved at runtime.')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('csp_policy')
                            ->info('Full policy string. null uses the bundle default, which keeps connect-src closed.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('headers')
                            ->info('Overrides merged over the defaults. A null value drops that header entirely.')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('captcha')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('operations')
                            ->info('Arithmetic operations the question may use: +, - or *.')
                            ->scalarPrototype()->end()
                            ->defaultValue(['+'])
                        ->end()
                        ->scalarNode('session_key')
                            ->info('Session key holding the expected answer.')
                            ->defaultValue('_math_captcha_answer')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('purge')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('batch_size')
                            ->info('Rows flushed at a time by core:purge. Lower it when the entities are heavy.')
                            ->min(1)
                            ->defaultValue(100)
                        ->end()
                        ->arrayNode('aliases')
                            ->info('Extra names core:purge answers to. Use it to keep a legacy name alive so a deployed crontab does not break.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('encryption_key')
                    ->info('Base64-encoded 32-byte key. Setting it registers Security\\Encryptor and the listener that feeds the encrypted_string DBAL type. Point it at an env var; never commit it.')
                    ->defaultNull()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
